Deprecated UiFramework.fronstages.clearFrontstageProviders
iTwin/appui pull request #1022
Opened 2024-09-11 12:51 UTC by MBudreviciusBentley

## Changes

Deprecated  `UiFramework.fronstages.clearFrontstageProviders()`  (suggested replacement `FrameworkFrontstages.clearFrontstageDefs()`)

## Testing

N/A

2024-09-11 14:48 UTC, GerardasB requested changes

2024-09-18 13:15 UTC, MBudreviciusBentley commented on ui/appui-react/src/appui-react/framework/FrameworkFrontstages.ts
> +   * @deprecated in 4.17.0. Use {@link FrameworkFrontstages.clearFrontstageDefs} instead.
Added such a method and add a test for `clearFronstages`

2024-09-18 14:10 UTC, GerardasB approved these changes

2024-09-18 14:10 UTC, GerardasB commented on ui/appui-react/src/test/frontstage/FrontstageManager.test.tsx
> +  it("clearFrontstages should clear frontstages and fronstageProviders", async () => {
```suggestion
  it("clearFrontstages should clear frontstages and frontstageProviders", async () => {
```

2024-09-18 14:10 UTC, GerardasB commented on ui/appui-react/src/test/frontstage/FrontstageManager.test.tsx
> +    expect(InternalFrontstageManager.activeFrontstageId).toEqual("");
There is a lot of overlap with other unit tests, let's test a single unit of code (described by the test name).
`defaultFrontstageConfig` in the below snipped can be imported from `"./FrontstageDef.test";`

```suggestion
    const frontstageProvider = new TestFrontstage();
    InternalFrontstageManager.addFrontstageProvider(frontstageProvider);
    InternalFrontstageManager.addFrontstage(defaultFrontstageConfig);
    expect(
      InternalFrontstageManager.hasFrontstage(frontstageProvider.id)
    ).toEqual(true);
    expect(
      InternalFrontstageManager.hasFrontstage(defaultFrontstageConfig.id)
    ).toEqual(true);

    InternalFrontstageManager.clearFrontstages();

    expect(
      InternalFrontstageManager.hasFrontstage(frontstageProvider.id)
    ).toEqual(false);
    expect(
      InternalFrontstageManager.hasFrontstage(defaultFrontstageConfig.id)
    ).toEqual(false);
```

2024-09-18 15:05 UTC, merged