Add condition to PropertyFilterBuilderRenderer to allow last rule deletion
iTwin/appui pull request #1034
Opened 2024-09-16 21:16 UTC by morganadrales

## Changes

Added a prop called `allowLastRuleDelete` that will enable the deletion of the last remaining rule in a group.

## Testing

Built and tested locally with the Pineapple groups/query-builder component.

2024-09-17 11:44 UTC, saskliutas requested changes
Looks good. Can you add unit test for `PropertyFilterBuilderActions.removeItem` in `FilterBuilderState.test.ts` to test the new behavior?

2024-09-17 16:04 UTC, morganadrales commented
> Looks good. Can you add unit test for `PropertyFilterBuilderActions.removeItem` in `FilterBuilderState.test.ts` to test the new behavior?

Added and also fixed a test that was failing in `FilterBuilderRule.test.tsx` due to not expecting that `allowLastRuleDelete` prop to be passed in the `removeRule` function

2024-09-18 07:33 UTC, GerardasB approved these changes
LGTM, describe the change in `NextVersion.md` as well

2024-09-18 07:54 UTC, saskliutas approved these changes

2024-09-18 19:53 UTC, merged