Update UI for components-react FilterBuilder
iTwin/appui pull request #686
Opened 2024-01-22 19:04 UTC by morganadrales

## Changes
Before:
![image](https://github.com/iTwin/appui/assets/85196633/79df94fb-5201-41d4-94ec-3a6a3ba4539d)

After:
![image](https://github.com/iTwin/appui/assets/85196633/15208899-4c21-4e24-9ce1-269ab822f1c4)

API changes include removal of nesting, as we will be able to support "IN" and "BETWEEN" operators instead.
Note: This branch is a fork of https://github.com/iTwin/appui/pull/576 where the sizes have been removed until iTwinUI's ButtonGroup is implemented for the EnumButtonGroupEditor.

## Testing
Updated tests to reflect the removal of nesting. Maintained the package's 100% test coverage.

2024-01-23 15:26 UTC, raplemie requested changes
Add a NextVersion.md entry for these changes, outside of the few comments, we seem to be pretty done with this!

2024-01-23 15:26 UTC, raplemie commented on ui/components-react/src/test/filter-builder/FilterBuilderRuleGroup.test.tsx
> +    rootGroup.operator = PropertyFilterRuleGroupOperator.Or;
On the other PR, there was a remark about mutating rootGroup, for this you could make a shallow copy of the shared group and change the copy operator.

2024-01-23 15:26 UTC, raplemie commented on ui/components-react/src/test/filter-builder/FilterBuilderRuleGroup.test.tsx
> +      group: rootGroup,
On the other PR, there was a remark about mutating `rootGroup`, I think it was missed in the branch.
```suggestion
    rootGroup.operator = PropertyFilterRuleGroupOperator.Or;
    const props: PropertyFilterBuilderRuleGroupRendererProps = {
      group: { ...rootGroup, operator: PropertyFilterRuleGroupOperator.Or },
```

2024-01-23 19:55 UTC, morganadrales commented on common/changes/@itwin/core-react/morgan-filter-builder_2024-01-12-17-01.json
Should I add a 4.9.0 entry? Or what version will this be making it into?

2024-01-23 21:05 UTC, raplemie commented on common/changes/@itwin/core-react/morgan-filter-builder_2024-01-12-17-01.json
There is a file named "NextVersion.md", just edit it in place, the numbering will be handled by the tooling.

2024-01-24 08:56 UTC, saskliutas requested changes

2024-01-24 08:56 UTC, saskliutas commented on ui/components-react/src/test/filter-builder/FilterBuilderRuleGroup.test.tsx
> +      group: rootGroupCopy,
```suggestion
    const props: PropertyFilterBuilderRuleGroupRendererProps = {
      group: { ...rootGroup, operator: PropertyFilterRuleGroupOperator.Or  },
```

2024-01-24 08:56 UTC, saskliutas commented on ui/components-react/src/test/filter-builder/FilterBuilderRuleGroup.test.tsx
> +      group: rootGroupCopy,
```suggestion
    const props: PropertyFilterBuilderRuleGroupRendererProps = {
      group: { ...rootGroup, operator: PropertyFilterRuleGroupOperator.Or },
```

2024-01-26 07:50 UTC, saskliutas approved these changes

2024-01-29 17:56 UTC, raplemie approved these changes
With this one last thing, good job, then done with this!

2024-01-29 17:56 UTC, raplemie commented on docs/changehistory/NextVersion.md
> +## Changes
Add the `changes` section in the table of content.

2024-01-29 19:58 UTC, merged